version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=backend
      - DB_PASSWORD=your_password
      - DB_NAME=api_db
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: api_db
      MYSQL_USER: backend
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
