name: Build and Push to GHCR

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/backend:latest .

      - name: Push image
        run: docker push ghcr.io/${{ github.repository_owner }}/backend:latest
